tap "supabase/tap"
brew "sqlite"
brew "tree"
brew "ansible"
brew "arp-scan"
brew "bat"
brew "btop"
brew "eza"
brew "fish"
brew "git"
brew "git-lfs"
brew "just"
brew "kubernetes-cli"
brew "utf8proc", args: ["HEAD"]
brew "neovim"
brew "notcurses"
brew "nushell"
brew "pipx"
brew "starship"
brew "stow"
brew "zoxide"
brew "supabase/tap/supabase", trusted: true
cask "bruno"
cask "db-browser-for-sqlite"
cask "kitty"
npm "corepack"
