#!/usr/bin/env bash

# 'touch' a file and make it executable
[ -z "$1" ] && echo "Need at least 1 argument: file name to create!" && exit -1

touch $1 && chmod u+x $1 || echo "Couldn't make file"&& exit 1
