# Disable Ctrl+S and Ctrl+Q
stty -ixon

# Path to your oh-my-zsh installation.
export ZSH="$ZDOTDIR/ohmyzsh"
# export SHELL=/usr/bin/zsh

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="lambda-mod"  #robbyrussel #gozilla  #half-life

# when using random theme
#echo "Current random theme: $RANDOM_THEME"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=3

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"


plugins=(git docker zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

export HISTFILE="$HOME/.cache/zsh_history"

source $HOME/.config/aliasrc
