#!/usr/bin/env bash

# "e" will make script exit if something fails
# "x" will print out every command and its result
# set -x #e

function printsl {
    echo "" # newline
    echo "$1"
    sleep 0.5
}

##### Update system && Instal Packages  #####
printsl "Updating system"
sudo apt update && sudo apt full-upgrade -y

printsl "Installing apt packages"
sudo apt install -y \
    alacritty apt-transport-https build-essential cheese \
    cmake code deepin-icon-theme fish gdb gnome-tweaks google-chrome-stable \
    gparted htop libdvd-pkg make mongodb neovim python3.8 \
    python3-pip python3-dev shellcheck sqlite3 sqlitebrowser tensorman \
    tree ttf-mscorefonts-installer ubuntu-restricted-extras \
    virtualbox virtualbox-dkms

#####  Reset Font Cache  ######
printsl "Reseting font cache"
sudo fc-cache -f -v

printsl "Installing flatpaks"
flatpak install flathub \
	postman \
	gitKraken \
    spotify \
	slack \
    discord \
    zoom

#####  Remove unneed apps  ######
printsl "Apt cleanup"
sudo apt purge --auto-remove -y geary
# clean up
sudo apt autoremove

#####  Python setup  #####
printsl "Setting up pip and pipenv"
python3.8 -m pip install -U pip
python3.8 -m pip install -U pipenv

printsl "Installing Jupyter Lab"
python3.8 -m pip install -U jupyterlab

#####  Install Dotnet Core 3.1  #####
printsl "Installing Dotnet Core 3.1"
wget https://packages.microsoft.com/config/ubuntu/19.10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt update
sudo apt install dotnet-sdk-3.1
printsl "Installing EF Core CLI Tools" && dotnet tool install --global dotnet-ef
rm packages-microsoft-prod.dev

#####  Install Node v12.x  #####
printsl "Installing Node JS v12.x"
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt install -y nodejs

##### Install "Diff So Fancy" #####
printsl "Installing 'diff-so-fancy' via npm"
sudo npm install -g diff-so-fancy

#####  Install deno  #####
# printsl "Installing Deno via curl"
# curl -fsSL https://deno.land/x/install/install.sh | sh

#####  Install Rust  #####
printsl "Installing Rust"
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

#####  Install Kite  #####
printsl "Installing kite"
bash -c "$(wget -q -O - https://linux.kite.com/dls/linux/current)"
