#!/usr/bin/env bash

function printsl() {
    echo "" # New Line
    echo $1
    sleep 0.5
}

cd "$DOTFILES/firefox-developer"

#####  Extract Archive  #####
tar -xf firefox.tar.xz

#####  Move to opt folder #####
mkdir -p /opt/firefox-developer
sudo mv firefox /opt/firefox-developer 

##### Move desktop file  #####
sudo mv firefox-developer.desktop /usr/share/applications/.
