[tools]
node = "lts"
pnpm = "latest"
zig = "latest"

# [settings]
# idiomatic_version_file_enable_tools = ["python"]
# python.uv_venv_auto = "source"

# [env]
# _.python.venv = { path = "{{config_root}}/.venv" }
